### ISSUE TITLE
CreateDbSetMock throwing Unsupported expression exception

### ISSUE THREAD

**Issue by TanvirArjel** [cup-of-tea-dot-be/entity-framework-core3-mock#3]
Here is my test method:

    public class EmployeeServiceTest
    {
        public static DbContextOptions<EmployeeDbContext> DummyOptions { get; } = new DbContextOptionsBuilder<EmployeeDbContext>().Options;
    
        private DbContextMock<EmployeeDbContext> _mockDbConext = new DbContextMock<EmployeeDbContext>(DummyOptions);

        private EmployeeService EmployeeService => new EmployeeService(_mockDbConext.Object);

        [Fact]
        public async Task GetEmployeeByIdAsyncTest()
        {
            // Arragne
            List<Employee> employees = new List<Employee>()
            {
                new Employee(){EmployeeId = 1, EmployeeName = "Tanvir"},
                new Employee(){EmployeeId = 2,EmployeeName = "Tanvir2"},
            };

            DbSetMock<Employee> usersDbSetMock = _mockDbConext.CreateDbSetMock(x => x.Employees, employees);

            // Act

            Employee employee = await EmployeeService.GetEmployeeByIdAsync(1);

            // Assert

        }
    }

Throwing the following exception:

>System.NotSupportedException : Unsupported expression: x => x.Employees
    Non-overridable members (here: EmployeeDbContext.get_Employees) may not be used in setup / verification expressions.

Stack Trace:

>Guard.IsOverridable(MethodInfo method, Expression expression)
    InvocationShape.ctor(LambdaExpression expression, MethodInfo method, IReadOnlyList`1 arguments, Boolean exactGenericTypeArguments)
    ExpressionExtensions.<Split>g__Split|5_0(Expression e, Expression& r, InvocationShape& p)
    ExpressionExtensions.Split(LambdaExpression expression)
    Mock.SetupRecursive[TSetup](Mock mock, LambdaExpression expression, Func`4 setupLast)
    Mock.Setup(Mock mock, LambdaExpression expression, Condition condition)
    Mock`1.Setup[TResult](Expression`1 expression)
    DbContextMock`1.CreateDbSetMock[TEntity](Expression`1 dbSetSelector, Func`3 entityKeyFactory, IEnumerable`1 initialEntities)
    DbContextMock`1.CreateDbSetMock[TEntity](Expression`1 dbSetSelector, IEnumerable`1 initialEntities)
    EmployeeServiceTest.GetEmployeeByIdAsyncTest() line 32
    --- End of stack trace from previous location where exception was thrown ---

**Note: I am using Entity Framework 3.1**

**Comment by huysentruitw** [comment]
Can you mark your `Employees` property as virtual in your `EmployeeDbContext`? The `Mock` library can't mock them otherwise.

**Comment by duhowise** [comment]
Adding the `virtual` key work on all my `DbSets` fixed this issue for me
